---

- name: Nginx - Setup flags compiled
  template:
    src: .nginx_compilation_flags.j2
    dest: "{{ nginx_build_tmp_dir }}/.nginx_compilation_flags"
  register: nginx_flags

- include: "build.yml"
  when: nginx_install_type == 'source' && when: nginx_flags.changed
