# file: nginx-build/tasks/modules/naxsi_module.yml

- name: Nginx Modules - Download the naxsi_module source
  get_url:
    url: "{{nginx_naxsi_url}}"
    dest: "{{ nginx_build_tmp_dir }}/nginx-naxsi-module.tar.gz"

- name: Nginx Modules - Unpack the naxsi_module source
  command: tar -xvzf {{ nginx_build_tmp_dir }}/nginx-naxsi-module.tar.gz chdir={{ nginx_build_tmp_dir }} creates={{ nginx_build_tmp_dir }}/naxsi-{{nginx_naxsi_version}}

- name: Nginx Modules - Make sure the naxsi_module configuration is up to date
  copy:
    src: files/naxsi_core.rules
    dest: "{{nginx_dir}}/naxsi_core.rules"
    owner: root
    group: root
    mode: 0644
