# file: nginx-build/tasks/modules/upload_progress_module.yml

# to be completed...

- name: Nginx Modules - Download the upload_progress_module source
  get_url:
    url: "{{nginx_upload_progress_url}}"
    dest: "{{ nginx_build_tmp_dir }}/nginx-upload-progress-module-{{nginx_upload_progress_version}}.tar.gz"

- name: Nginx Modules - Unpack the upload_progress_module source
  command: tar -xvzf {{ nginx_build_tmp_dir }}/nginx-upload-progress-module-{{nginx_upload_progress_version}}.tar.gz chdir={{ nginx_build_tmp_dir }} creates={{ nginx_build_tmp_dir }}/nginx-upload-progress-module-{{nginx_upload_progress_version}}

- name: Nginx Modules - Make sure the upload_progress_module configuration is updated
  template:
    src: templates/modules/upload_progress.j2
    dest: "{{nginx_dir}}/sites-available/upload_progress"
    owner: root
    group: root
    mode: 0644
